[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyos-dan"
version = "0.1.1"
description = "A zero-import Python operating-system interface"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
pyos = ["native/*.c", "native/*.h", "native/decoders/linux/*.c", "native/decoders/linux/*.h"]
